### ISSUE TITLE
Allow docker pull by digest

### ISSUE THREAD

**Issue by zsolt-haraszti** [gesellix/docker-client#27]
Great library!

I would like to be able to pull an image specified by its digest, the equivalent of (by example):

  docker pull nginx@sha256:b555f8c64ab4e85405e0d8b03f759b73ce88deb802892a3b155ef55e3e832806

In fact I would like to do this from the gradle-docker-plugin. Any plans for adding support for digests?

**Comment by gesellix** [comment]
hey,

thanks for filing the issue!

You should now be able to pull by digest when using the current releases:

- docker client: `'de.gesellix:docker-client:2016-05-05T11-03-00'`
- gradle docker plugin: `id "de.gesellix.docker" version "2016-05-05T13-15-11"`

In case I missed anything, please re-open or add another issue!
