### ISSUE TITLE
Docker Swarm mode 

### ISSUE THREAD

**Issue by jamroks** [gesellix/docker-client#34]
Does the library support the APIs introduced in docker swarm 1.12 ?  
i mean the new: 
  swarm, services , node , task  ans so on ...APIs

Cheers

**Comment by jamroks** [comment]
Sorry i just saw that in the roadmap.md  . thanks.
looking forward to the support of : 

- docker service ps
- docker service scale
- docker swarm join-token 

Cheers

**Comment by gesellix** [comment]
@jamroks for `docker swarm join-token` you'll find the relevant bits there: https://github.com/gesellix/docker-client/blob/0c42b20e076839fb75b2d42daf82365e179ad59a/client/src/main/groovy/de/gesellix/docker/client/DockerClient.groovy#L233

more to come :-)

**Comment by gesellix** [comment]
`docker service ps` is available at https://github.com/gesellix/docker-client/blob/56a3206bc8fcc854878a5d8fc6d5270a61efb77e/client/src/main/groovy/de/gesellix/docker/client/DockerClient.groovy#L275

**Comment by gesellix** [comment]
`docker service scale` is available at https://github.com/gesellix/docker-client/blob/56a3206bc8fcc854878a5d8fc6d5270a61efb77e/client/src/main/groovy/de/gesellix/docker/client/DockerClient.groovy#L265

Note: this one is implemented for a single service, in contrast to the official Docker client.

**Comment by gesellix** [comment]
The artifact with all mentioned commands is available as `de.gesellix:docker-client:2016-12-10T23-39-48`
