### ISSUE TITLE
non-blocking docker logs

### ISSUE THREAD

**Issue by sgrell** [gesellix/docker-client#431]
Is there a way to use the `DockerClient.logs` command in a non-blocking way?

The current method delegates the call to `ContainerApi.containerLogs` where the command is executed and runs blocking until there is either no more data or the timeout is exceeded. In our scenario however, we are waiting for a specific log entry but there will be more log entries afterwards. So currently we always have to wait for the timeout which is very high and it is usually not necessary to wait that long.

It would be nice to have an option that runs asynchronously, calls the callback for every new log entry and runs until the timeout is exceeded or we cancel it.

**Comment by gesellix** [comment]
A new `waitForLogEvent(...)` method is available on the default branch, with a preview release as GitHub packages `"de.gesellix:docker-client:2023-03-12T22-35-35"`. An official package at Maven Central will be released soonish. Feel free to leave some feedback here, if anything should be added or changed before the release.

**Comment by sgrell** [comment]
As far as I understand your idea, the callback is called once for every `logFrame` as long as the callback returns `false`. Once it returns `true` the `waitFor` terminates and the flow continues. 

That sounds good to me and is quite similar to our current implementation, that however requires a bit of boilerplate code on our side, that we would love to get rid of.

**Comment by gesellix** [comment]
Yes, I tried to make it work like you originally suggested. There's no API to cancel it, though, but your Predicate/matcher implementation could return `true` depending on your own requirements or by an external signal.
The new integration test (see the referencing commit) is probably quite similar to your implementation.
I'm going to release an update on Maven Central during this week.

**Comment by gesellix** [comment]
... "during this week" being a somewhat stretchy goal 😬 

The release is now available as version [2023-03-28T00-05-00](https://github.com/gesellix/docker-client/releases/tag/v2023-03-28T00-05-00).
