### ISSUE TITLE
Does docker service need X-Registry-Auth header?

### ISSUE THREAD

**Issue by pekajota** [gesellix/docker-client#45]
Hello,

Trying to create a service with an image from a private repository but docker rejects it. Apparently this has to do with the registry authentication. The ManageServiceClient.createService does not let you pass base64 authentication details as ManageImageClient.pull does. Is this by design or a limitation?

Thanks

**Comment by gesellix** [comment]
@pekajota This is only a current limitation - I simply didn't implement it yet. If you like, you might create a pull request to add the appropriate header as optional parameter similar to the pull() implementation you already mentioned?

**Comment by gesellix** [comment]
With version `2017-07-02T23-30-20` you can pass the base64 encoded auth config like this:

````
dockerClient.createService(<service config>, [EncodedRegistryAuth: "base64..."])
````

Please give it a try!

**Comment by gesellix** [comment]
@pekajota I'm going to close this issue. If something doesn't work, please leave a note here. Thanks!
