### ISSUE TITLE
Support for ECC client certs provided by Docker EE UCP

### ISSUE THREAD

**Issue by svInfra17** [gesellix/docker-client#46]
Docker Universal Control Plane allows user to download client bundle which contains TLS cert files to connect docker CLI to it. The bundle contains client keypairs in ECC (Elliptic curve cryptography) algorithm format. Using these certs causes  

`java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: Invalid RSA private key` .

**Comment by gesellix** [comment]
ECDSA support has been added with https://github.com/gesellix/docker-client/commit/7c7d9f5cc294666b01999cf01d22c5ef0013655b.
Can you please check the new release `2017-07-19T21-12-05`?

**Comment by svInfra17** [comment]
Thanks @gesellix, The authentication with ECC client certs worked with `2017-07-19T21-12-05` release.
But faced issue with this release while pulling image from private docker repository. 
I am using `[EncodedRegistryAuth: "base64..."]` introduced in  Release `2017-07-02T23-30-20`

**Comment by gesellix** [comment]
@svInfra17 would you mind submitting another issue with more details (logs/example code/...) for the authentication problem? You can get more detailed logs when setting the log level for the package `de.gesellix.docker` to debug. Thanks!
