### ISSUE TITLE
Support for X-Registry-Auth in Docker run()

### ISSUE THREAD

**Issue by svInfra17** [gesellix/docker-client#47]
Hi,
Currently dockerClient.run() fails if the specified image is hosted on private docker registry. It will be great help if somebody adds support for it.

Thanks.

**Comment by gesellix** [comment]
@svInfra17 hey, thanks for raising that issue! I'll have a look into it soonish.

**Comment by gesellix** [comment]
Can you give the fresh release `2017-08-10T22-04-09` a try? The `run()` got another parameter to pass the base64 encoded authentication. I'll need to cleanup the class and method interfaces, but you should be able to use it in the current implementation. Please leave some feedback here whether it's working in your environment or not. Thanks!

**Comment by gesellix** [comment]
@svInfra17 did you have a chance to verify whether the new `run(...)` parameter would fit your needs?

**Comment by svInfra17** [comment]
Thanks @gesellix. Fix worked as expected.

**Comment by gesellix** [comment]
great, thanks for the feedback!
