### ISSUE TITLE
docker-client version for legacy swarm

### ISSUE THREAD

**Issue by vishal-biyani** [gesellix/docker-client#57]
Did docker-client supported legacy swarm (before Docker Engine 1.12) in past ? If yes, may I know the version of docker-client that had support?

**Comment by gesellix** [comment]
Sorry, this docker-client never had support for the standalone Docker Swarm. Do you need specific endpoints? Due to the untyped internal details, adding new endpoints is quite simple, all I need is some kind of api documentation.

**Comment by gesellix** [comment]
The docs at https://docs.docker.com/swarm/swarm-api/ say:

> The Docker Swarm API is mostly compatible with the Docker Remote API. ...

So, in general there might be minor differences, but most endpoints should work out of the box. Have you already tried to use the docker-client on standalone swarm?

**Comment by gesellix** [comment]
Closing now, since your question has been answered. Feel free to leave a comment in case you'd like to see support for the legacy swarm.
