### ISSUE TITLE
validateExternalNetworks disallows non-swarm networks for stacks

### ISSUE THREAD

**Issue by mstump** [gesellix/docker-client#66]
As of [17.06.0](https://github.com/docker/cli/pull/132) host and bridge networks are allowed for stacks, but this library is flagging [non-swarm networks as invalid](https://github.com/gesellix/docker-client/blob/master/client/src/main/groovy/de/gesellix/docker/client/stack/DeployConfigReader.groovy#L630).

```java.lang.IllegalStateException: network bridge is declared as external, but is not in 'swarm' scope.```

**Comment by gesellix** [comment]
@mstump thanks for this issue, I'm going to fix it in #70 along with another fix for network aliases.

**Comment by gesellix** [comment]
fix is contained in https://bintray.com/gesellix/docker-utils/docker-client/2018-06-02T10-49-31
