### ISSUE TITLE
DeployConfigReader does not populate envFile from ComposeFileReader (env_file from yam)

### ISSUE THREAD

**Issue by jkamke** [gesellix/docker-client#67]
Though it is loaded in the ComposeConfig it does not carry on to the resulting service

**Comment by gesellix** [comment]
`env_file` needs to be read at https://github.com/gesellix/docker-client/blob/f71bb90237ea8e768381bfec318b739acb6f0947/client/src/main/groovy/de/gesellix/docker/client/stack/DeployConfigReader.groovy#L153

**Comment by gesellix** [comment]
The new release is available as `de.gesellix:docker-client:2019-04-07T18-59-35`.
Thanks for your patience!
