### ISSUE TITLE
createSecret fails for data with any byte > 127

### ISSUE THREAD

**Issue by berndos** [gesellix/docker-client#69]
While this line of Kotlin works ok
```
DockerClientImpl("unix:///var/run/docker.sock").createSecret("foo",126,127)
```

this one does not
```
DockerClientImpl("unix:///var/run/docker.sock").createSecret("foo",126,127,128.toByte())
```
There appears to be a serialization issue, as an error is thrown by the docker-engine:
```
Mai 29 01:20:06 saul dockerd[16044]: time="2018-05-29T01:20:06.564082527+02:00" level=error msg="Handler for POST /secrets/create returned error: json: cannot unmarshal number -128 into Go struct field SecretSpec.Data of type uint8"
```

The go-client is somehow able to handle this, as this again fails:
```
DockerClientImpl("unix:///var/run/docker.sock")
                        .createSecret("foo",
                                URL("https://pbs.twimg.com/profile_images/862037907862765568/pYgBswUk_400x400.jpg").readBytes(), mapOf())
```
but this works:
```
bernd@saul:/tmp$ docker secret create foo pYgBswUk_400x400.jpg 
mcej984yd3buol5cakht09kz8
```

**Comment by gesellix** [comment]
🤔 that's surprising, I'll have to dig deeper to find out why some bytes trigger a problem. Maybe the go-client encodes them in a special way before passing them to the engine.

**Comment by gesellix** [comment]
Looks like the secrets need to be base64 encoded...

**Comment by gesellix** [comment]
fix is contained in https://bintray.com/gesellix/docker-utils/docker-client/2018-06-02T10-49-31
