### ISSUE TITLE
Add exemple

### ISSUE THREAD

**Issue by cbourree** [gesellix/docker-client#73]
Please can you add exemple of how create service with your docker client ?

**Comment by gesellix** [comment]
Did you find the unit test at https://github.com/gesellix/docker-client/blob/388f9a7b461890dfa882dbfa0ba0d59a8548f07c/client/src/test/groovy/de/gesellix/docker/client/service/ManageServiceClientTest.groovy#L37 ?

I can add a more concise example in the Readme. Do you have a specific use case I should consider?

**Comment by gesellix** [comment]
Please follow #44 (or #149): I'm working on a type safe api, so that your IDE will help. Integration tests will remain as working example.
